name: Lootin
version: ${project.version}
main: com.github.sachin.lootin.Lootin
api-version: 1.16
authors: [ sachingorkar ]
softdepend: [Terra,CustomStructures,Oh_the_dungeons_youll_go,PlaceholderAPI,ProtocolLib,Realistic_World,BetterStructures,WorldGuard]
description: Loot per player
api: []
folia-supported: true


permissions:
  lootin.breakchest.bypass:
    default: op
  lootin.command.reload:
    default: op  
  lootin.breakelytraitemframe.bypass:
    default: op  
  lootin.command.rwggive:
    default: op 
  lootin.command.set:
    default: op  