name: Lootin
version: ${project.version}
main: com.github.sachin.lootin.Lootin
api-version: 1.16
authors: [ sachingorkar ]
softdepend: [Terra,CustomStructures,Oh_the_dungeons_youll_go,PlaceholderAPI,ProtocolLib,Realistic_World,BetterStructures,WorldGuard]
description: Loot per player
api: []
folia-supported: true


permissions:
  lootin.breakchest.bypass:
    default: op
  lootin.breakelytraitemframe.bypass:
    default: op
  lootin.preventfilling.bypass:
    default: op
  lootin.command.*:
    default: op
    children:
      lootin.command.reload: true
      lootin.command.rwggive: true
      lootin.command.set: true
      lootin.command.info: true
      lootin.command.clear: true